### ISSUE TITLE
Add multilanguage support

### ISSUE THREAD

**Issue by felixfischer** [amperser/proselint#308]
It would be great if rules for others languages could be added to the linter.

**Comment by vnglst** [comment]
Yes that would be cool, I'd love to add support for Dutch for instance!

**Comment by casperl** [comment]
Perusing the source code, I can spot the issue with why other language support will be a problem.  There are sequence of files under checks that each contains certain lexical checks and rules.  It is not merely a question of translating but one of starting from scratch for each language.  Such content requires person(s) with a great deal of expertise in any given language.

That does not mean that proselint is not of critical importance for other languages, especially Afrikaans which I am writing in.

My question is, do you have the infrastructure in proselint in place to handle multiple languages if I set about organising content creation for those applicable files in Afrikaans?

Alternatively, a variation of proselint per language may be equally viable such as a future proseling-af for or proselint-de since there are certainly language specific issues (such as Anglicisms) that English does not have.   The more I think about it, that will be the way to go, a common core functionality and then a language specific version since even English is not universal, there are variations in English between South African, British, Australian, Canadian, US and second-language speaker English that a good lint checking tool should be able to recognise.

**Comment by felixfischer** [comment]
this went stale – closing the issue as I am no longer using the repo
