### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by jrmain** [amperser/proselint#458]
I've looked for proselint documentation here on Github and elsewhere and come up empty. Any chance we'll be getting something along those lines soon? Mainly I'm interested in the command line options. What does `--clean` do? What syntax do I use for `.proselintrc`?

**Comment by suchow** [comment]
Hi, we haven't spent much if any time thinking about how to best document the system, but agree it's important. I looked briefly and found a nice site with best practices in documentation (http://write-the-docs.readthedocs.org/writing/beginners-guide-to-docs/), so that can be something to aim for. I've opened a PR (#461) that we can use to build up the documentation a bit.

Could I convince you to create a list of all the documentation that you think would be helpful?

**Comment by jrmain** [comment]
The basics are 'how to install it' and 'how to use it'. For the former, basic instructions for Linux systems that already have Python, then any special steps required for major systems like OSX and Windows. You've already got a start on the Github page. The 'how to use' docs should at the very least cover the command line options, as otherwise we are literally forced to guess and/or experiment.

**Comment by sigmavirus24** [comment]
I'd add a suggestion for "how to configure it". It took me a while to puzzle out that there was no project-local configuration, so I couldn't check in my desired configuration for proselint without some [trickery](https://github.com/sigmavirus24/github3.py/pull/836).
