### ISSUE TITLE
Ubuntu package is not available

### ISSUE THREAD

**Issue by DavidDreher** [amperser/proselint#915]
```
>>sudo add-apt-repository universe
'universe' distribution component is already enabled for all sources.

>>sudo apt install python3-proselint
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-proselint is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-proselint' has no installation candidate

```

**Comment by ShilohMy** [comment]
You don't having to do anything.

**Comment by dylan-k** [comment]
I was able to install using Ubuntu today, so it seems this issue may be resolved.

**Comment by Nytelife26** [comment]
Things like this are the responsibility of those that set up the packages for such distributions. It would be wiser to raise the issue with the package maintainers listed for `python3-proselint` in the Ubuntu repository. Although, we are open to having a closer relationship with those that package proselint for various systems, so if they wish to step forward in order to tie things together better that would be a welcome change.
