### ISSUE TITLE
42 Pull Requests Dating Back a Few Years

### ISSUE THREAD

**Issue by dylan-k** [amperser/proselint#968]
Is this an abandoned project, or is there anything to be done to more quickly review the community input?

**Comment by tbm** [comment]
@suchow can you comment on the status and future of this project?

**Comment by suchow** [comment]
Interesting question. 

It's abandonware in the sense that nobody is actively looking after it right now. But we haven't given up hope, just turned our attention elsewhere. 

I'm not sure what can be done to more quickly review community input. I think any help in maintaining and contributing to the project would be appreciated.

Thoughts, @mpacer?

**Comment by Nytelife26** [comment]
> I'm not sure what can be done to more quickly review community input. I think any help in maintaining and contributing to the project would be appreciated.

I am a linguist reading this almost a year later. I found proselint today and it intrigues me greatly. Are you still looking for a maintainer? If so, I would be more than happy to pick up where amperser left off.

**Comment by suchow** [comment]
@Nytelife26 Yes. I will take any help you are willing to give. 

There's quite a lot of low-hanging fruit available for picking, including (1) getting the Travis build to pass, (2) upgrading dependencies, (3) fixing the obvious bugs that the community has flagged in the issue tracker. Then there are more substantive changes like making proselint Markdown-aware, adding new checks, improving existing checks, etc. And then the really big project in the back of my mind is integrating with spaCy, which would open up the possibility of POS-aware rules, special treatment of names entities, and more.

The only thing that I think will require some discussion is about community-submitted checks, some of which you can find in the open PRs. The problem is that some of these don't jibe with the proselint ethos, which is to try as much as possible to keep the false alarm rate low, and it'll require some work to either fix them or work with the submitter to get them in shape (or, alas, reject and close them). Maybe we can have a few conversations about this as things arise.

If this is something you're still interested in, let me know at jws@stevens.edu. My guess is that there are a bunch of people hanging around here who might also be interested in helping, it just requires some initial time and attention to get things back on track.

**Comment by Nytelife26** [comment]
@suchow I left you an email, currently awaiting a response.

**Comment by Nytelife26** [comment]
As this is a duplicate issue, it seems appropriate to aggregate future discussion into the most active and most recent replacement - #1140.
